### ISSUE TITLE
Solemnity of the Nativity of St. John the Baptist : June 23, 2022

### ISSUE THREAD

**Issue by scriptura** [pejulian/romcal#364] opened 2022-06-25 09:49 UTC
Good morning,

There is a calculation error in your calendar: for this year 2022 the Nativity of St. John the Baptist must be scheduled for June 23, which is not the case.

Best regards.

**Comment by tukusejssirs** [comment] 2022-06-25 09:52
Thanks, @Scriptura, I’ll close this as a duplicate of #363.

**Closed as completed** 2022-06-25 09:52 UTC
